from display_data.methods.display_title_results import display_title_results
from display_data.methods.display_body_results import display_body_results
from display_data.methods.display_top_comments_results import display_top_comments_results
from display_data.methods.display_sub_comments_results import display_sub_comments_results
from display_data.methods.display_votes_results import display_votes_results
